// pub mod binary_search;
// pub mod bit_full_serach;
// pub mod devide_and_conquer;
// pub mod difference_cumulative;
// pub mod dynamic_programming;
// pub mod euclidean_algorithm;
// pub mod full_search;
// pub mod merge_sort;
// pub mod monte_carlo;
// pub mod newton_method;
// pub mod primality_test;
// pub mod sieve_of_erastosthenes;
// pub mod sort;
// pub mod depth_first_search;
// pub mod breadth_first_search;
pub mod repeated_squaring;
